version: "3.7"
 
services:
 
 mysql:
  image: mysql:latest
  restart: always
  container_name: Full202086309
  volumes:
   - db_data:/var/lib/mysql
  ports:
   - "3306:3306"
  networks:
   BridgeZad1A:
    ipv4_address: 10.0.10.3 
  environment:
        MYSQL_ROOT_PASSWORD: "root"
        MYSQL_DATABASE: "DKarpiuk"
        MYSQL_USER: "admin"
        MYSQL_PASSWORD: "admin"
 java:
  image: muchomor125/repozytorium:latest
  stdin_open: true
  container_name: JavaContainer
  depends_on:
    - mysql
  networks:
   - BridgeZad1A
 
networks:
  BridgeZad1A:
   driver: bridge
   ipam:
    config:
     - subnet: 10.0.10.0/24

volumes:
 db_data: {}
